[package]
name = "users"
description = "Library for getting information on Unix users and groups"

authors = [ "ogham@bsago.me" ]
documentation = "https://docs.rs/users/users/"
homepage = "https://github.com/ogham/rust-users"
license = "MIT"
readme = "README.md"
version = "0.6.0"

[dependencies]
libc = "0.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"
redox_users = { "git" = "https://github.com/redox-os/users.git" }